### ISSUE TITLE
No notifications with beta13

### ISSUE THREAD

**Issue by devlich** [Andrewerr/NextcloudServices#52] opened 2023-02-28 14:09 UTC
Hi ! Thanks for this great app. It's the only app that works for me. I unfortunately had to downgrade to beta12 since the beta13 does not even appear in the list of app that need permissions to notify. I'm using the main nextcloud app method for connecting but I've tried the other one and I have the same issue. I'm on android 13 and I using Fdroid to install NextcloudServices.

**Comment by Rikj000** [comment] 2023-02-28 14:13
Duplicate of #51

**Comment by Andrewerr** [comment] 2023-02-28 14:22
Hello @devlich. You are welcome :)
Yes this is known issue(#51) which has a fix and it was just tested working(thanks to @Rikj000). So I would try to make a new release as soon as possible, so fix would be available with next F-Droid update

**Comment by devlich** [comment] 2023-02-28 14:30
Hi @Rikj000 and @Andrewerr,
Sorry It didn't seams to me that it is was the same issue as #51 since in my case the app is not greyed out, it's just not in the list. I didn't see the app-debug.apk link though. I will give it a try, thank your very much.

**Comment by Andrewerr** [comment] 2023-02-28 14:38
@devlich if you would like to use bleeding-edge version you should download a CI artifact. Here is the instruction how to do it: https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts . Also artifact APK is unsigned, so it should be installed via `adb` as Android disallows installing apps without signature from SystemUI.
GitHub Actions run on which app is confirmed to work is https://github.com/Andrewerr/NextcloudServices/actions/runs/4136114311 .

**Comment by devlich** [comment] 2023-02-28 14:43
> @devlich if you would like to use bleeding-edge version you should download a CI artifact. Here is the instruction how to do it: https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts . Also artifact APK is unsigned, so it should be installed via `adb` as Android disallows installing apps without signature from SystemUI. GitHub Actions run on which app is confirmed to work is https://github.com/Andrewerr/NextcloudServices/actions/runs/4136114311 .

Thank you @Andrewerr, I will definitely try that.

**Comment by Andrewerr** [comment] 2023-03-01 10:44
Closing issue as a version including fix for it has just released

**Closed by Andrewerr** 2023-03-01 10:44 UTC
Labels: duplicate
