### ISSUE TITLE
Allow http:// addresses in the local network

### ISSUE THREAD

**Issue by andenbeere** [Andrewerr/NextcloudServices#5] opened 2021-07-27 15:01 UTC
Hi there,

I'd like to use your app to get Nextcloud Talk notifications from my Nextcloud instance. I use it only within my local network and for simplicity's sake have a bare http endpoint.

Your app currently seems to expect https connections, so whatever I insert in the Nextcloud address field, it does not connect to my Nextcloud.

Do you think it might be possible to allow both http and https? Keep up the good work and count on me for testing if my request gets implemented. 

Best regards
Michael

**Comment by Andrewerr** [comment] 2021-07-28 14:55
Hello. 
Thank you for suggesstion. I would implement a switch wich would force using insecure connection(it does not seem to be very hard to do so :))

But always remember: even in your local network better to use encrypted connection, so you can generate a self-signed certificate and add it to your Android CA storage

**Comment by Andrewerr** [comment] 2021-07-28 14:56
Features to add:
* [ ] An option for switching between `http://` and `https://`

**Comment by andenbeere** [comment] 2021-07-31 07:12
Thank you! Looking forward to your solution.

**Comment by Andrewerr** [comment] 2021-08-01 18:33
The feautre is added in release v1.0-beta8(just published it), so I am closing this issue.

**Closed by Andrewerr** 2021-08-01 18:33 UTC
Labels: enhancement

**Comment by andenbeere** [comment] 2021-08-04 15:54
I just tested the new release. I now now can connect to my http endpoint and get notifications. Thank you for that!

Only for a better understanding: The notifications don't seem to be "linked" to other Nextcloud apps on the phone. So if I tap the notifications, I don't jump to the Nextcloud Talk app or anywhere else. Also if I am inside the Talk app and get a Talk call, no popup appears where I can accept or reject the call. So this is the desired behaviour of your app, a plain and isolated popup with the notification, right? (BTW, that's fine for me).

This is on a Google Pixel 3a with LineageOS 17.1, no Google Play services, no MicroG. Nextcloud main app and Nextcloud Talk installed and working.

**Comment by Andrewerr** [comment] 2021-08-09 14:27
Thank you for notifying about this bug :)
Yes it works as intended: opening app or URL when notication is clicked is not yet implemented(as for calls I am not even sure that it is possible some how to make Talk open call window from another app). @penguin86 has created issue about this, so if you like you can monitor the progress in issue #10
